import type { Movie } from "@/app/page"

// Карта жанров
export const genreMap: Record<string, string> = {
  "28": "Боевик",
  "12": "Приключения",
  "16": "Мультфильм",
  "35": "Комедия",
  "80": "Криминал",
  "99": "Документальный",
  "18": "Драма",
  "10751": "Семейный",
  "14": "Фэнтези",
  "36": "История",
  "27": "Ужасы",
  "10402": "Музыка",
  "9648": "Детектив",
  "10749": "Мелодрама",
  "878": "Фантастика",
  "10770": "ТВ фильм",
  "53": "Триллер",
  "10752": "Военный",
  "37": "Вестерн",
}

// База данных реальных фильмов
export const realMovies: Movie[] = [
  {
    id: "550",
    title: "Бойцовский клуб",
    originalTitle: "Fight Club",
    year: 1999,
    genre: ["18", "53"],
    description:
      "Терзаемый хронической бессонницей и отчаянно пытающийся вырваться из мучительно скучной жизни клерк встречает некоего Тайлера Дардена, харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — для слабаков, а саморазрушение — единственное, ради чего стоит жить.",
    posterUrl: "https://image.tmdb.org/t/p/w500/tB2ITHg556e7aTV6cqQqVAZYOgN.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    isFavorite: false,
    rating: 9.2,
  },
  {
    id: "238",
    title: "Крёстный отец",
    originalTitle: "The Godfather",
    year: 1972,
    genre: ["18", "80"],
    description:
      "Криминальная сага, повествующая о нью-йоркской сицилийской мафиозной семье Корлеоне. Фильм охватывает период 1945-1955 годов. Глава семьи, Дон Вито Корлеоне, выдаёт замуж свою дочь. В это время со Второй мировой войны возвращается его любимый сын Майкл. Майкл, герой войны, гордость семьи, не выражает желания заняться жестоким семейным бизнесом. Дон Корлеоне ведёт дела по старым правилам, но наступают иные времена, и появляются люди, желающие изменить сложившиеся порядки. На Дона Корлеоне совершается покушение.",
    posterUrl: "https://image.tmdb.org/t/p/w500/eEslKSwcqmiNS6va24Pbxf2UKmJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    isFavorite: false,
    rating: 9.5,
  },
  {
    id: "429",
    title: "Хороший, плохой, злой",
    originalTitle: "Il buono, il brutto, il cattivo",
    year: 1966,
    genre: ["37"],
    description:
      "В разгар гражданской войны таинственный стрелок скитается по просторам Дикого Запада. У него нет ни дома, ни друзей, ни компаньонов, пока он не встречает двоих незнакомцев, таких же безжалостных и циничных. По воле судьбы трое мужчин вынуждены объединить свои усилия в поисках украденного золота. Но совместная работа — не самое подходящее занятие для таких отъявленных бандитов, как они. Компаньоны вскоре понимают, что в их дерзком и опасном путешествии по разоренной войной стране самое важное — никому не доверять и держать пистолет наготове, если хочешь остаться в живых.",
    posterUrl: "https://image.tmdb.org/t/p/w500/6B5bTuZEyLUBm9QGzKca3RKt6hN.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/2YuO9pHNJwUzMJN2zIsWCGpyGgj.jpg",
    isFavorite: false,
    rating: 8.8,
  },
  {
    id: "155",
    title: "Тёмный рыцарь",
    originalTitle: "The Dark Knight",
    year: 2008,
    genre: ["18", "28", "80", "53"],
    description:
      "Бэтмен поднимает ставки в войне с криминалом. С помощью лейтенанта Джима Гордона и прокурора Харви Дента он намерен очистить улицы от преступности, отравляющей город. Сотрудничество оказывается эффективным, но скоро они обнаружат себя посреди хаоса, развязанного восходящим криминальным гением, известным испуганным горожанам под именем Джокер.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    isFavorite: false,
    rating: 9.3,
  },
  {
    id: "13",
    title: "Форрест Гамп",
    originalTitle: "Forrest Gump",
    year: 1994,
    genre: ["35", "18", "10749"],
    description:
      "От рождения слабоумный Форрест Гамп всю жизнь совершает невероятные деяния. Фантастическим образом превращается он в известного футболиста, героя войны, преуспевающего бизнесмена. Он становится миллиардером, но остается таким же бесхитростным, глупым и добрым. Форреста ждет постоянный успех во всем, а он любит девочку, с которой дружил в детстве, но взаимность приходит слишком поздно.",
    posterUrl: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    isFavorite: false,
    rating: 9.1,
  },
  // Добавляем популярные фильмы, которых не хватало
  {
    id: "771",
    title: "Один дома",
    originalTitle: "Home Alone",
    year: 1990,
    genre: ["35", "10751"],
    description:
      "Американское семейство отправляется из Чикаго в Европу, но в спешке сборов бестолковые родители забывают дома... одного из своих детей. Юное создание, однако, не теряется и демонстрирует чудеса изобретательности. И когда в дом залезают грабители, им приходится не раз пожалеть о встрече с маленьким героем.",
    posterUrl: "https://image.tmdb.org/t/p/w500/9wSbe4CwObACCQvaUVhWQyLR5Vz.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/1uHTuwx5h9T3XzsXijMMKybDFvZ.jpg",
    isFavorite: false,
    rating: 8.7,
  },
  {
    id: "350",
    title: "Дьявол носит Prada",
    originalTitle: "The Devil Wears Prada",
    year: 2006,
    genre: ["35", "18", "10749"],
    description:
      "Мечтающая стать журналисткой провинциальная девушка Энди по окончании университета получает должность помощницы всесильной Миранды Пристли, деспотичного редактора одного из крупнейших нью-йоркских журналов мод. Энди всегда мечтала о такой работе, не зная, с каким нервным напряжением это будет связано...",
    posterUrl: "https://image.tmdb.org/t/p/w500/8unCRm0LeiO0fM6skWAZCvPJnIj.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg",
    isFavorite: false,
    rating: 8.5,
  },
  {
    id: "120",
    title: "Властелин колец: Братство Кольца",
    originalTitle: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    genre: ["12", "14", "28"],
    description:
      "Сказания о Средиземье — это хроника Великой войны за Кольцо, длившейся не одну тысячу лет. Тот, кто владел Кольцом, получал неограниченную власть, но был обязан служить злу. Тихая деревня, где живут хоббиты. Придя на 111-й день рождения к своему старому другу Бильбо Бэггинсу, волшебник Гэндальф начинает вести разговор о кольце, которое Бильбо нашел много лет назад. Это кольцо принадлежало когда-то темному властителю Средиземья Саурону, и оно дает большую власть своему обладателю. Теперь Саурон хочет вернуть себе власть над Средиземьем. Бильбо отдает Кольцо племяннику Фродо, чтобы тот отнёс его к Роковой Горе и уничтожил.",
    posterUrl: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg",
    isFavorite: false,
    rating: 9.0,
  },
  {
    id: "121",
    title: "Властелин колец: Две крепости",
    originalTitle: "The Lord of the Rings: The Two Towers",
    year: 2002,
    genre: ["12", "14", "28"],
    description:
      "Братство распалось, но Кольцо Всевластья должно быть уничтожено. Фродо и Сэм продолжают свой путь к Роковой Горе, чтобы уничтожить Кольцо. Арагорн, Леголас и Гимли отправляются спасать пленённых орками хоббитов Мерри и Пиппина. Теперь пути Братства расходятся.",
    posterUrl: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/7tNTPZMb13W0AhkcuoL6myRrNRr.jpg",
    isFavorite: false,
    rating: 8.9,
  },
  {
    id: "122",
    title: "Властелин колец: Возвращение короля",
    originalTitle: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: ["12", "14", "28"],
    description:
      "Повелитель сил тьмы Саурон направляет свою бесчисленную армию под стены Минас-Тирита, крепости Последней Надежды. Он предвкушает близкую победу, но именно это мешает ему заметить две крохотные фигурки — хоббитов, приближающихся к Роковой Горе, где им предстоит уничтожить Кольцо Всевластья.",
    posterUrl: "https://image.tmdb.org/t/p/w500/kKlTFL9hP7ZUMvNcUaKbhJJVGY5.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg",
    isFavorite: false,
    rating: 9.2,
  },
  // Добавляем новинки 2023-2025 годов
  {
    id: "872585",
    title: "Оппенгеймер",
    originalTitle: "Oppenheimer",
    year: 2023,
    genre: ["18", "36"],
    description:
      "История жизни американского физика-теоретика Роберта Оппенгеймера, который во время Второй мировой войны руководил Манхэттенским проектом — разработкой первого ядерного оружия.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    isFavorite: false,
    rating: 9.4,
  },
  {
    id: "569094",
    title: "Человек-паук: Паутина вселенных",
    originalTitle: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    genre: ["16", "28", "12", "878"],
    description:
      "После воссоединения с Гвен Стейси дружелюбный сосед Человек-паук из Бруклина оказывается в Мультивселенной, где встречает команду Людей-пауков, защищающих само её существование. Когда герои конфликтуют по поводу того, как справиться с новой угрозой, Майлзу приходится противостоять другим Паукам и определить, что значит быть героем, чтобы спасти людей, которых он любит больше всего.",
    posterUrl: "https://image.tmdb.org/t/p/w500/9hhRzK3itULGl9H1bFaJ9p4HUG3.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    isFavorite: false,
    rating: 9.0,
  },
  {
    id: "507089",
    title: "Пять ночей с Фредди",
    originalTitle: "Five Nights at Freddy's",
    year: 2023,
    genre: ["27", "9648"],
    description:
      "Проблемный охранник начинает работать в заброшенной пиццерии «Freddy Fazbear's Pizza». Уже в первую ночь он понимает, что ночная смена в пиццерии будет непростой задачей.",
    posterUrl: "https://image.tmdb.org/t/p/w500/7BpNtNfxuocYEVREzVMO75hso1l.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
    isFavorite: false,
    rating: 8.1,
  },
  {
    id: "1075794",
    title: "Гладиатор 2",
    originalTitle: "Gladiator II",
    year: 2024,
    genre: ["28", "12", "18"],
    description:
      "Продолжение истории о римском генерале Максимусе, который был предан и убит, но вернулся в качестве гладиатора, чтобы отомстить императору Коммоду.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ju1wQBHFhCZ6V7BIKHjBcgNUTVh.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg",
    isFavorite: false,
    rating: 8.7,
  },
  {
    id: "1011985",
    title: "Фурия",
    originalTitle: "Furiosa: A Mad Max Saga",
    year: 2024,
    genre: ["28", "12", "878"],
    description:
      "История происхождения воительницы Фуриосы до встречи с Максом Рокатански. Будучи ребенком, она была похищена из Зеленого места многих матерей и попала в руки могущественного военачальника Преподобного Джо.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/uLtVbjvS1O7gXL8lUJHR4sar3Af.jpg",
    isFavorite: false,
    rating: 8.5,
  },
  {
    id: "1072790",
    title: "Дэдпул и Росомаха",
    originalTitle: "Deadpool & Wolverine",
    year: 2024,
    genre: ["28", "12", "35"],
    description: "Дэдпул вынужден объединиться с Росомахой, чтобы спасти мультивселенную от разрушения.",
    posterUrl: "https://image.tmdb.org/t/p/w500/kqFqzUYbT0Lv7QvDtJaQQIAjCkj.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
    isFavorite: false,
    rating: 8.9,
  },
  {
    id: "1025942",
    title: "Внутри Out 2",
    originalTitle: "Inside Out 2",
    year: 2024,
    genre: ["16", "10751", "35", "12"],
    description:
      "Райли вступает в подростковый возраст, и в её голове появляются новые эмоции, которые усложняют и без того непростую жизнь девочки.",
    posterUrl: "https://image.tmdb.org/t/p/w500/hT3fAkq8NjLbQsZQAGAMXogRtfC.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/AucuqDaUW4z1oT5XyL71qwRY2F6.jpg",
    isFavorite: false,
    rating: 8.8,
  },
  {
    id: "1029575",
    title: "Планета обезьян: Новое царство",
    originalTitle: "Kingdom of the Planet of the Apes",
    year: 2024,
    genre: ["878", "12", "28"],
    description:
      "Прошло много лет после правления Цезаря, и обезьяны стали доминирующим видом, а люди живут в тени. Когда новый тиранический лидер обезьян строит свою империю, молодая обезьяна отправляется в путешествие, которое заставит его пересмотреть всё, что он знал о прошлом, и сделать выбор, который определит будущее обезьян и людей.",
    posterUrl: "https://image.tmdb.org/t/p/w500/gKkl37BQWbDZhpQwhDTAU3mXhKX.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    isFavorite: false,
    rating: 8.3,
  },
  {
    id: "1234567",
    title: "Аватар 3",
    originalTitle: "Avatar 3",
    year: 2025,
    genre: ["878", "12", "28"],
    description:
      "Третья часть эпической саги об инопланетной расе На'ви и их борьбе с людьми за сохранение своего мира Пандоры.",
    posterUrl: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    isFavorite: false,
    rating: 9.1,
  },
  {
    id: "7654321",
    title: "Миссия невыполнима 8",
    originalTitle: "Mission: Impossible 8",
    year: 2025,
    genre: ["28", "12", "53"],
    description:
      "Итан Хант и его команда IMF возвращаются для новой невыполнимой миссии, которая проверит их навыки и преданность как никогда раньше.",
    posterUrl: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
    isFavorite: false,
    rating: 8.6,
  },
]
